name: macos

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  build_matrix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-2204
          - ubuntu-2404
    uses: ./.github/workflows/common.yml
    with:
      os: ${{ matrix.version }}
    secrets: inherit
