name: Spack build

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * *"

jobs:
  build_macos:
    strategy:
      fail-fast: false
      matrix:
        include:

         - os: macos-14
           xcode: "15.0.1"
           compiler: "apple-clang@15.0.0"
           default: false

         - os: macos-14
           xcode: "16.0.0"
           compiler: "apple-clang@16.0.0"
           default: true

         - os: macos-15
           xcode: "16.0.0"
           compiler: "apple-clang@16.0.0"
           default: true

    uses: ./.github/workflows/spack.yml
    with:
      os: ${{ matrix.os }}
      xcode: ${{ matrix.xcode }}
      compiler: ${{ matrix.compiler }}
      default: ${{ matrix.default }}
    secrets: inherit

  # build_native:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #
  #        - os: ubuntu-22.04
  #          compiler: gcc@11.4.0
  #          default: true
  #
  #        - os: ubuntu-22.04
  #          compiler: clang@14.0.0
  #          default: false
  #
  #        - os: ubuntu-24.04
  #          compiler: gcc@13.3.0
  #          default: true
  #
  #        - os: ubuntu-24.04
  #          compiler: clang@18.1.3
  #          default: false
  #
  #   uses: ./.github/workflows/spack.yml
  #   with:
  #     os: ${{ matrix.os }}
  #     compiler: ${{ matrix.compiler }}
  #     default: ${{ matrix.default }}
  #   secrets: inherit

  build_container:
    strategy:
      fail-fast: false
      matrix:

        include:
          - image: ghcr.io/acts-project/alma9-base:sha-cc4444b
            compiler: gcc@11.5.0
            default: true

          - image: ghcr.io/acts-project/ubuntu2204:sha-cc4444b
            compiler: gcc@11.4.0
            default: true

          - image: ghcr.io/acts-project/ubuntu2204:sha-cc4444b
            compiler: clang@14.0.0
            default: false

          - image: ghcr.io/acts-project/ubuntu2404:sha-cc4444b
            compiler: gcc@13.3.0
            default: true

          - image: ghcr.io/acts-project/ubuntu2404:sha-cc4444b
            compiler: clang@18.1.3
            default: false

          - image: ghcr.io/acts-project/ubuntu2404_clang19:sha-cc4444b
            compiler: clang@19.1.6
            default: false

    uses: ./.github/workflows/spack.yml
    with:
      os: ubuntu-latest
      image: ${{ matrix.image }}
      compiler: ${{ matrix.compiler }}
      default: ${{ matrix.default }}
    secrets: inherit
