name: Builds

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:


jobs:
  build_matrix:
    strategy:
      fail-fast: false
      matrix:
        image: ["none"]
        os:
         - macos-14
         - macos-15
         - ubuntu-22.04
         - ubuntu-24.04

        include:
         - os: ubuntu-24.04
           image: ghcr.io/acts-project/alma9-base:67
    uses: ./.github/workflows/common.yml
    with:
      os: ${{ matrix.os }}
      image: ${{ matrix.image }}
    secrets: inherit
