name: Builds

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:


jobs:
  build_matrix:
    strategy:
      fail-fast: false
      matrix:
        image: [none]
        include:
         - os: macos-14
         - os: macos-15
         - os: ubuntu-22.04
         - os: ubuntu-24.04
         - os: ubuntu-24.04
           image: ghcr.io/acts-project/alma9-base:67
    uses: ./.github/workflows/common.yml
    with:
      os: ${{ matrix.os }}
      image: ${{ matrix.image == 'none' && '' || matrix.image }}
    secrets: inherit
