name: Spack build

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * *"

jobs:
  build_macos:
    strategy:
      fail-fast: false
      matrix:
        include:

         - os: macos-14
           xcode: "15.0.1"
           compiler: "apple-clang@15.0.0"
           publish: false

         - os: macos-14
           xcode: "16.0.0"
           compiler: "apple-clang@16.0.0"
           publish: true

         - os: macos-15
           xcode: "16.0.0"
           compiler: "apple-clang@16.0.0"
           publish: true

    uses: ./.github/workflows/spack.yml
    with:
      os: ${{ matrix.os }}
      xcode: ${{ matrix.xcode }}
      compiler: ${{ matrix.compiler }}
      publish: ${{ matrix.publish }}
    secrets: inherit

  build_native:
    strategy:
      fail-fast: false
      matrix:
        include:

         - os: ubuntu-22.04
           compiler: gcc@12.3.0
           publish: true

         - os: ubuntu-24.04
           compiler: gcc@13.2.0
           publish: true

         - os: ubuntu-24.04
           compiler: clang@18.1.3
           publish: false

    uses: ./.github/workflows/spack.yml
    with:
      os: ${{ matrix.os }}
      compiler: ${{ matrix.compiler }}
      publish: ${{ matrix.publish }}
    secrets: inherit

  build_container:
    strategy:
      fail-fast: false
      matrix:

        include:
          - image: ghcr.io/acts-project/alma9-base:67
            compiler: gcc@11.4.1
            publish: true

    uses: ./.github/workflows/spack.yml
    with:
      os: ubuntu-latest
      image: ${{ matrix.image }}
      compiler: ${{ matrix.compiler }}
      publish: ${{ matrix.publish }}
    secrets: inherit
