name: Spack build

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * *"

jobs:
  build_macos:
    strategy:
      fail-fast: false
      matrix:
        include:

         - os: macos-14
           xcode: "16.2.0"
           compiler: "apple-clang@16.0.0"
           default: true

         - os: macos-15
           xcode: "16.2.0"
           compiler: "apple-clang@16.0.0"
           default: true

         - os: macos-15
           xcode: "16.3.0"
           compiler: "apple-clang@17.0.0"
           default: true

    uses: ./.github/workflows/spack.yml
    with:
      os: ${{ matrix.os }}
      xcode: ${{ matrix.xcode }}
      compiler: ${{ matrix.compiler }}
      default: ${{ matrix.default }}
    secrets: inherit

  build_container:
    strategy:
      fail-fast: false
      matrix:

        include:
          - image: ghcr.io/acts-project/alma9-base:80
            compiler: gcc@11.5.0
            os: ubuntu-latest
            default: true

          - image: ghcr.io/acts-project/ubuntu2404:80
            compiler: gcc@13.3.0
            os: ubuntu-latest
            default: true

          - image: ghcr.io/acts-project/ubuntu2404:80
            compiler: llvm@18.1.3
            os: ubuntu-latest
            default: false

          - image: ghcr.io/acts-project/ubuntu2404_clang19:80
            compiler: llvm@19.1.7
            os: ubuntu-latest
            default: false

          - image: ghcr.io/acts-project/ubuntu2404:80
            compiler: gcc@13.3.0
            os: ubuntu-24.04-arm
            default: false

    uses: ./.github/workflows/spack.yml
    with:
      os: ${{ matrix.os }}
      image: ${{ matrix.image }}
      compiler: ${{ matrix.compiler }}
      default: ${{ matrix.default }}
    secrets: inherit
