name: Spack build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * *"

jobs:
  build_macos:
    strategy:
      fail-fast: false
      matrix:
        include:
         - os: macos-14
           xcode: "15.0.1"
         - os: macos-14
           xcode: "16.0.0"
         - os: macos-15
           xcode: "16.0.0"
    uses: ./.github/workflows/spack.yml
    with:
      os: ${{ matrix.os }}
      xcode: ${{ matrix.xcode }}
    secrets: inherit

  build_native:
    strategy:
      fail-fast: false
      matrix:
        os:
         - ubuntu-22.04
         - ubuntu-24.04
    uses: ./.github/workflows/spack.yml
    with:
      os: ${{ matrix.os }}
    secrets: inherit

  build_container:
    strategy:
      fail-fast: false
      matrix:
        image:
          - ghcr.io/acts-project/alma9-base:67
    uses: ./.github/workflows/spack.yml
    with:
      os: ubuntu-latest
      image: ${{ matrix.image }}
    secrets: inherit

  collect_locks:
    needs: [build_macos, build_native, build_container]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all spack.lock files
        uses: actions/download-artifact@v4
        with:
          pattern: spack.lock-*
          merge-multiple: true
          path: spack-locks

      - name: List spack.lock files
        run: |
          ls -al
          ls -al spack-locks

      - name: Upload combined locks
        uses: actions/upload-artifact@v4
        with:
          name: spack-locks
          path: spack-locks
          if-no-files-found: error


      - name: Download all spack.lock files
        uses: actions/download-artifact@v4
        with:
          pattern: spack-*.lock
          merge-multiple: true
          path: spack-locks-combined

      - name: Copy lock files and commit
        run: |
          # Copy all lock files, overwriting existing ones
          cp -rf spack-locks-combined/* spack-locks/

          # Configure git
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          # Add, commit and push changes
          git add spack-locks/
          git commit -m "Update spack lock files [skip ci]"
          git push origin "HEAD:${GITHUB_REF#refs/heads/}"
