name: Build dependencies

on:
  workflow_call:
    inputs: 
      os:
        required: true
        type: string
      image:
        required: false
        type: string
        default: ""

jobs:

  build:
    runs-on: "${{ inputs.os }}"
    container:
      image: ${{ inputs.image == 'none' && '' || inputs.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2

      - name: Apply spack patch
        working-directory: spack
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          curl https://patch-diff.githubusercontent.com/raw/spack/spack/pull/47370.patch | git am

      - name: Remove XCode versions to save disk
        if: startsWith(inputs.os, 'macos')
        run: |
          echo "Disk spaces before cleanup"
          sudo df -h
          echo "Searching for Xcode versions:"
          find /Applications -name "Xcode_*" -maxdepth 1 -mindepth 1
          # https://github.com/actions/runner-images/issues/2840#issuecomment-2334584217
          echo "Remove all but the latest Xcode..."
          find /Applications/ -name "Xcode*" | sort -r | tail --lines=+2 | xargs rm -rf
          echo "Available Xcode versions after removal:"
          find /Applications -name "Xcode_*" -maxdepth 1 -mindepth 1
          echo "Disk spaces after cleanup"
          sudo df -h

      - name: Remove packages to save disk
        if: startsWith(inputs.os, 'ubuntu')
        run: |
          df -h
          sudo apt-get update
          echo "Listing 25 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 25
          echo "Removing large packages"
          sudo apt-get remove -y '^dotnet-.*' || true
          sudo apt-get remove -y '^llvm-.*' || true
          sudo apt-get remove -y '^libllvm-.*' || true
          sudo apt-get remove -y azure-cli || true
          sudo apt-get remove -y google-cloud-cli || true
          sudo apt-get remove -y google-chrome-stable || true
          sudo apt-get remove -y firefox || true
          sudo apt-get remove -y powershell || true
          sudo apt-get remove -y mono-devel || true
          sudo apt-get remove -y '^temurin.*' || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          rm -rf /usr/share/dotnet/
          df -h

      - name: Run spack build
        run: |
          eval `spack env activate --sh .`
          spack find
          spack concretize
          spack install --no-check-signature

      - name: Push packages and update index
        run: |
          spack -e . mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache
          spack -e . buildcache push --base-image ubuntu:22.04 --unsigned --update-index local-buildcache
        if: ${{ !cancelled() }}
