name: Build dependencies

on:
  workflow_call:
    inputs: 
      os:
        required: true
        type: string

jobs:

  build:
    runs-on: "${{ inputs.os }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2

      - run: |
          sudo mkdir -p /opt/spack /opt/view
          sudo chown $USER /opt/spack
          sudo chown $USER /opt/view
      - run: spack -e . install --no-check-signature
