name: Build dependencies

on:
  workflow_call:
    inputs: 
      os:
        required: true
        type: string

env:
  BUILD_DIR: ${{ github.workspace }}/build
  INSTALL_DIR: ${{ github.workspace }}/dependencies

  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_MAXSIZE: 10G

  CXX_STANDARD: "20"

jobs:

  build:
    runs-on: "${{ inputs.os }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2

      - run: spack -e . install --no-check-signature
