name: Build dependencies

on:
  workflow_call:
    inputs: 
      os:
        required: true
        type: string

jobs:

  build:
    runs-on: "${{ inputs.os }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2

      # - run: |
      #     sudo mkdir -p /opt/spack /opt/view
      #     sudo chown $USER /opt/spack
      #     sudo chown $USER /opt/view

      - name: Run spack build
        run: |
          eval `spack env activate --sh .`
          spack find
          spack concretize
          spack install --no-check-signature

      - name: Push packages and update index
        run: |
          spack -e . mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache
          spack -e . buildcache push --base-image ubuntu:22.04 --unsigned --update-index local-buildcache
        if: ${{ !cancelled() }}
