name: Build dependencies

on:
  workflow_call:
    inputs: 
      os:
        required: true
        type: string

jobs:

  build:
    runs-on: "${{ inputs.os }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2

      # - run: |
      #     sudo mkdir -p /opt/spack /opt/view
      #     sudo chown $USER /opt/spack
      #     sudo chown $USER /opt/view
      #
#
      - name: Remove XCode versions to save disk
        if: startsWith(inputs.os, 'macos')
        run: |
          echo "Disk spaces before cleanup"
          sudo df -h
          echo "Searching for Xcode versions:"
          find /Applications -name "Xcode_*" -maxdepth 1 -mindepth 1
          # https://github.com/actions/runner-images/issues/2840#issuecomment-2334584217
          echo "Remove all but the latest Xcode..."
          find /Applications/ -name "Xcode*" | sort -r | tail --lines=+2 | xargs rm -rf
          echo "Available Xcode versions after removal:"
          find /Applications -name "Xcode_*" -maxdepth 1 -mindepth 1
          echo "Disk spaces after cleanup"
          sudo df -h

      - name: Remove packages to save disk
        if: startsWith(inputs.os, 'ubuntu')
        run: |
          df -h
          sudo apt-get update
          echo "Listing 25 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 25
          echo "Removing large packages"
          function nuke {
            $(sudo dpkg --status $1 &> /dev/null)
            if [[ $? -eq 0 ]]; then
              sudo apt-get remove -y $1
            fi
          }
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          nuke -y azure-cli
          nuke -y google-cloud-cli
          nuke -y google-chrome-stable
          nuke -y firefox
          nuke -y powershell
          nuke -y mono-devel
          sudo apt-get remove -y '^temurin.*'
          sudo apt-get autoremove -y
          sudo apt-get clean
          rm -rf /usr/share/dotnet/
          df -h

      - name: Run spack build
        run: |
          eval `spack env activate --sh .`
          spack find
          spack concretize
          spack install --no-check-signature

      - name: Push packages and update index
        run: |
          spack -e . mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache
          spack -e . buildcache push --base-image ubuntu:22.04 --unsigned --update-index local-buildcache
        if: ${{ !cancelled() }}
