name: macOS

on: [push, pull_request]

env:
  # SPEC: acts@main+dd4hep+examples+fatras+geant4+hepmc3+json+pythia8+python+tgeo+unit_tests ^root~opengl~x
  SPEC: nlohmann-json

jobs:
  build_spack:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.0'

      - uses: actions/checkout@v3

      - run: brew install --build-from-source ./spack.rb

      - name: Cache
        uses: actions/cache@v3
        with:
          path: /usr/local/Cellar/spack/develop/opt/spack/
          key: ${{ runner.os  }}_spack_${{ github.sha }}
          restore-keys: |
            ${{ runner.os  }}_spack_

      - run: spack spec ${SPEC}
      - run: spack install --only dependencies ${SPEC}


      - uses: actions/upload-artifact@v3
        with:
          name: spack_cache
          path: /usr/local/Cellar/spack/develop/opt/spack/

