name: macOS

on: [push, pull_request]

env:
  SPEC: acts+dd4hep+edm4hep+examples+fatras+geant4+hepmc3+json+odd+pythia8+python+tgeo+unit_tests ^root~opengl~x

jobs:
  build_boost:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.0'

      - run: brew install spack

      - run: spack spec ${SPEC}
      - run: spack install --only dependencies ${SPEC}
