name: macOS

on:
  - push

jobs:
  build:
    runs-on: macos-10.15
    env:
      ROOT_VERSION: 6.20.00
      GEANT4_VERSION: 10.6.1
      DD4HEP_VERSION: 01-11-02
      INSTALL_DIR: acts-deps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: >
          brew install boost eigen cmake xerces-c
          && mkdir -p $INSTALL_DIR
      - name: Build ROOT
        run: >
          curl -SL https://root.cern/download/root_v${ROOT_VERSION}.source.tar.gz | tar -xzC . 
          && mv root-* root_src 
          && mkdir root_build && cd root_build 
          && cmake ../root_src 
          -DCMAKE_CXX_STANDARD=17 
          -DCMAKE_INSTALL_PREFIX=../${INSTALL_DIR} 
          -Dx11=ON 
          -Dfftw3=ON 
          -Dgdml=ON 
          -Dminuit2=ON 
          -Dopengl=ON 
          -Droofit=ON 
          -Dxml=ON 
          && make -j2
          && make install 
          && rm -rf /root_src /root_build 

      - name: Build Geant4
        run: >
          curl -SL https://github.com/Geant4/geant4/archive/v${GEANT4_VERSION}.tar.gz | tar -xzC .
          && mv geant4-* geant4_src
          && mkdir geant4_build && cd geant4_build
          && cmake ../geant4_src
          -DGEANT4_USE_GDML=ON
          -DGEANT4_BUILD_CXXSTD=17
          -DCMAKE_INSTALL_PREFIX=../${INSTALL_DIR}
          && make -j2
          && make install
          && rm -rf /geant4_src /geant4_build

      - name: Build DD4hep
        run: >
          curl -SL https://github.com/AIDASoft/DD4hep/archive/v${DD4HEP_VERSION}.tar.gz | tar -xzC .
          && mv DD4hep-* dd4hep_src
          && mkdir dd4hep_build && cd dd4hep_build
          && cmake ../dd4hep_src
          -DDD4HEP_USE_GEANT4=ON
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_INSTALL_PREFIX=../${INSTALL_DIR}
          -DBUILD_DOCS=OFF
          && make -j2
          && make install
          && rm -rf /dd4hep_src /dd4hep_build

      - uses: actions/upload-artifact@v1
        with:
          name: libs
          path: acts-deps


