name: macOS

on:
  - push

jobs:
  build:
    runs-on: macos-10.15
    env:
      ROOT_VERSION: 6.20.00
      GEANT4_VERSION: 10.6.1
      DD4HEP_VERSION: 01-11-02
      INSTALL_DIR: acts-deps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: >
          brew install boost eigen cmake xerces-c
          && mkdir -p $INSTALL_DIR
      - name: Build ROOT
        run: >
          curl -SL https://root.cern/download/root_v${ROOT_VERSION}.source.tar.gz | tar -xzC . 
          && mv root-* root_src 
          && mkdir root_build && cd root_build 
          && cmake ../root_src 
          -DCMAKE_CXX_STANDARD=17 
          -DCMAKE_INSTALL_PREFIX=../${INSTALL_DIR} 
          -Dx11=ON 
          -Dfftw3=ON 
          -Dgdml=ON 
          -Dminuit2=ON 
          -Dopengl=ON 
          -Droofit=ON 
          -Dxml=ON 
          && make -j2
          && make install 

      - name: Build Geant4
        run: >
          curl -SL https://github.com/Geant4/geant4/archive/v${GEANT4_VERSION}.tar.gz | tar -xzC .
          && mv geant4-* geant4_src
          && mkdir geant4_build && cd geant4_build
          && cmake ../geant4_src
          -DGEANT4_USE_GDML=ON
          -DGEANT4_BUILD_CXXSTD=17
          -DCMAKE_INSTALL_PREFIX=../${INSTALL_DIR}
          && make -j2
          && make install

      - name: Build DD4hep
        run: >
          curl -SL https://github.com/AIDASoft/DD4hep/archive/v${DD4HEP_VERSION}.tar.gz | tar -xzC .
          && mv DD4hep-* dd4hep_src
          && mkdir dd4hep_build && cd dd4hep_build
          && cmake ../dd4hep_src
          -DDD4HEP_USE_GEANT4=ON
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_INSTALL_PREFIX=../${INSTALL_DIR}
          -DBUILD_DOCS=OFF
          && make -j2
          && make install

      - name: Build HepMC
        run: >
          curl -SL https://gitlab.cern.ch/hepmc/HepMC3/-/archive/3.2.1/HepMC3-3.2.1.tar.gz | tar -xzC .
          && mv HepMC* hepmc_src
          && mkdir hepmc_build && cd hepmc_build
          && cmake ../hepmc_src
          -DCMAKE_INSTALL_PREFIX=../${INSTALL_DIR}
          -DHEPMC3_ENABLE_PYTHON=OFF
          && make -j2
          && make install

      - name: Build HepPDT
        run: >
          curl -SL http://home.thep.lu.se/~torbjorn/pythia8/pythia8244.tgz | tar -xzC .
          && mv HepPDT* heppdt_src
          && cd heppdt_src
          && ./configure --prefix=$PWD/../${INSTALL_DIR}
          && make -j2
          && make install

      - name: Build Pythia8
        run: >
          curl -SL http://home.thep.lu.se/~torbjorn/pythia8/pythia8244.tgz | tar -xzC .
          && mv pythia8244 pythia8_src
          && cd pythia8_src
          && ./configure --prefix=$PWD/../${INSTALL_DIR}
          && make -j2
          && make install


      - name: Make tarball
        run: cd acts-deps && tar zcvf ../deps.tar.gz .

      - uses: actions/upload-artifact@v1
        with:
          name: libs
          path: deps.tar.gz


