name: Build script

on: 
  - push
  # - pull_request

env:
  SRC_DIR: ${{ github.workspace }}/src
  BUILD_DIR: ${{ github.workspace }}/build
  INSTALL_DIR: ${{ github.workspace }}/install

  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_MAXSIZE: 10G


jobs:
  build_all:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo ./install_prereq_ubuntu.sh
          sudo apt-get install -y ccache

      - name: Cache restore
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: builddir-${{ runner.os }}-${{ github.job }}-r1
          restore-keys: |
            builddir-${{ runner.os }}-${{ github.job }}-r1
            builddir-${{ runner.os }}-${{ github.job }}-

      - name: Build
        run: |
          ccache -z
          cmake -S . -B build \
          -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
          -DCMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
          ccache -s

      - uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: install


      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ${{ env.CCACHE_DIR }}
          key: builddir-${{ runner.os }}-${{ github.job }}-r1
