name: Build script

on: 
  - push
  # - pull_request

env:
  SRC_DIR: ${{ github.workspace }}/src
  BUILD_DIR: ${{ github.workspace }}/build
  INSTALL_DIR: ${{ github.workspace }}/install

  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_MAXSIZE: 10G


jobs:
  build_all:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essentials ninja ccache

      - name: Cache restore
        uses: actions/cache/restore@v3
        with:
          key: builddir-${{ runner.os }}-${{ github.job }}-r1
          restore-keys: |
            builddir-${{ runner.os }}-${{ github.job }}-r1
            builddir-${{ runner.os }}-${{ github.job }}-

      - name: Build
        run: >
          ccache -z
          ./build_all.sh $BUILD_DIR $INSTALL_DIR
          ccache -s

      - uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: install


      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ${{ env.BUILD_DIR }}
          key: builddir-${{ runner.os }}-${{ github.job }}-r1
